---
## Author
author:
  name: Рамазанов Абуталим Абдулмеджидович
  studID: 1032252477
  group: НПИбд-02-25
  email: 1032252477@pfur.ru
license: "CC BY"

## Title
title: "Отчет по лабораторной работе №4"
subtitle: "Дисциплина: Архитектура компьютера"
---

# Цель работы

Освоение процедуры компиляции и сборки программ, написанных на ассемблере NASM

# Выполнение лабораторной работы
Рассмотрим пример простой программы на языке ассемблера NASM. Традиционно первая
программа выводит приветственное сообщение Hello world! на экран. создадим каталог для работы с программами на языке ассемблера NASM и перейдем в каталог:

[Создание каталога](./image/1.png){#fig:001 width=70%}

Создадим текстовый файл с именем hello.asm

[Создаем текстовый файл](./image/2.png){#fig:001 width=70%}

Откроем этот файл с помощью любого текстового редактора, например, gedit

[Открываем файл через gedit](./image/3.png){#fig:001 width=70%}

и введем в него следующий текст:

[Программа Hello World](./image/4.png){#fig:001 width=70%}

NASM превращает текст программы в объектный код. Например, для компиляции приве-
дённого выше текста программы «Hello World» необходимо написать: nasm -f elf hello.asm
Проверяем создался ли объектный файл с помощью команды ls

[Проверка созданного файла](./image/5.png){#fig:001 width=70%}

Выполним следующую команду:
nasm -o obj.o -f elf -g -l list.lst hello.asm

[Преобразуем файл hello.asm в obj.o](./image/6.png){#fig:001 width=70%}

Чтобы получить исполняемую программу, объектный файл необходимо передать на обработку компоновщику:

[Команда ld](./image/7.png){#fig:001 width=70%}

Проверяем создался ли файл hello

[Проверка созданного файла](./image/8.png){#fig:001 width=70%}

Ключ -o с последующим значением задаёт в данном случае имя создаваемого исполняе-
мого файла. Выполним следующую команду: ld -m elf_i386 obj.o -o main

[Задаем имя исполняемого файла](./image/9.png){#fig:001 width=70%}

Запустить на выполнение созданный исполняемый файл, находящийся в текущем каталоге,
можно, набрав в командной строке: ./hello

[Запуск программы](./image/10.png){#fig:001 width=70%}

#Выполнение самостоятельной работы

В каталоге ~/work/arch-pc/lab04 с помощью команды cp создайте копию файла
hello.asm с именем lab4.asm

[Создаем копию](./image/11.png){#fig:001 width=70%}

С помощью любого текстового редактора внесите изменения в текст программы в
файле lab4.asm так, чтобы вместо Hello world! на экран выводилась строка с вашими
фамилией и именем.

[Выводим ФИ](./image/12.png){#fig:001 width=70%}

#Вывод

В ходе этой лабораторной работы мы познакомились с языком ассемблера NASM и запустили две програмы
