---
## Author
author:
  name: Рамазанов Абуталим Абдулмеджидович
  studID: 1032252477
  group: НПИбд-02-25
  email: 1032252477@pfur.ru
license: "CC BY"

## Title
title: "Отчет по лабораторной работе №7"
subtitle: "Дисциплина: Архитектура компьютера"
---

# Цель работы

Освоение команд условного и безусловного переходов. Наработка умений кодирования программ при содействии переходов. Ознакомление с ролью и форматом файла листинга.

# Выполнение лабораторной работы
Создаем каталог для программам лабораторной работы № 7, перейдем в него и создадим файл lab7-1.asm:

[Создание каталога и файла](./image/1.png){#fig:001 width=70%}

Заполняем файл в соответствии с листингом 7.1

[Заполняем файл](./image/2.png){#fig:001 width=70%}

Проверяем результат при запуске исполняемого файла

[Смотрим результат](./image/3.png){#fig:001 width=70%}

Изменяем файл в соответствии с листингом 7.2

[Изменяем файл](./image/4.png){#fig:001 width=70%}

Запускаем и проверяем его работу

[Запускаем файл](./image/5.png){#fig:001 width=70%}

Создаем файл lab7-2.asm в каталоге ~/work/arch-pc/lab07. Заполнем в соответствии с листингом 7.2

[Создаем и заполняем файл](./image/6.png){#fig:001 width=70%}

Запускаем файл lab7-2.asm

[Запускаем файл](./image/7.png){#fig:001 width=70%}

Создаем файл листинга для программы из файла lab7-2.asm указав ключ -l и запускаем его с помощью команды  mcedit lab7-2.lst

[Создание листинга для программы и его запуск](./image/8.png){#fig:001 width=70%}

Строка 33: 0000001D — адрес в сегменте кода, BB01000000 — машинный код, mov ebx, 1 — присвоение переменной ebx значения 1.
Строка 34: 00000022 — адрес в сегменте кода, B804000000 — машинный код, mov eax, 4 — присвоение переменной eax значения 4.
Строка 35: 00000027 — адрес в сегменте кода, CD80 — машинный код, int 80h — вызов ядра.

Откроем файл с программой lab7-2.asm и в любой инструкции с двумя операндами удаляем один операнд. 

[Убираем операндум](./image/9.png){#fig:001 width=70%}

Выполняем трансляцию с получением файла листинга:

[Трансляция](./image/10.png){#fig:001 width=70%}

Запускаем листинг и изучаем его

[Запускаем листинг](./image/11.png){#fig:001 width=70%}

#Самостоятельная работа
Вариант - 18

Создаем новый файл

[Новый файл](./image/12.png){#fig:001 width=70%}

Напишем программу нахождения наименьшей из 3 целочисленных переменных 𝑎,𝑏 и.

[Пишем программу](./image/13.png){#fig:001 width=70%}

Запускаем программу и смотрим как она работает

[Запуск программы](./image/14.png){#fig:001 width=70%}

Создаем новый файл

[Новый файл](./image/15.png){#fig:001 width=70%}

Напишем программу, которая для введенных с клавиатуры значений 𝑥 и 𝑎 вычисляет значение заданной функции 𝑓(𝑥) и выводит результат вычислений.

[Пишем программу](./image/16.png){#fig:001 width=70%}

Запускаем программу и смотрим как она работает

[Запуск программы](./image/17.png){#fig:001 width=70%}

#Вывод

Мы познакомились с структурой файла листинге и изучили условный и безусловный переход
