---
## Author
author:
  name: Рамазанов Абуталим Абдулмеджидович
  studID: 1032252477
  group: НПИбд-02-25
  email: 1032252477@pfur.ru
license: "CC BY"

## Title
title: "Отчет по лабораторной работе №5"
subtitle: "Дисциплина: Архитектура компьютера"
---

# Цель работы

изучить основы инструкции mov в ассемблере и научиться пользоваться программой Midnight Commander.

# Выполнение лабораторной работы

Откроем Midnight Commander

[Вводим в консоль команду mc](./image/1.png){#fig:001 width=70%}

С помощью ↑ , ↓ и Enter перейдем в каталог ~/work/arch-pc созданный при выполнении ЛБ №4

[Переходим в каталог](./image/2.png){#fig:001 width=70%}

С помощью F7 создаем папку lab05 и переходим в созданный каталог.

[Переходим папку lab05](./image/3.png){#fig:001 width=70%}

Используя строку ввода и командой touch создаем файл lab5-1.asm

[создаем файл lab5-1.asm](./image/4.png){#fig:001 width=70%}

С помощью F4 откроем файл lab5-1.asm для редактирования во встроенном редакторе. Введем программу из листинга

[Открываем файл и вводим программу](./image/5.png){#fig:001 width=70%}

С помощью F3 откроем файл lab5-1.asm для просмотра. Убедимся, что файл содержит текст программы.

[Проверяем файл на наличие программы](./image/6.png){#fig:001 width=70%}

Оттранслируем текст программы lab5-1.asm в объектный файл. Выполним компоновку объектного файла и запустим получившийся исполняемый файл. Программа выводит строку 'Введите строку:' и ожидает ввода с клавиатуры. На запрос введем свое ФИО.

[Проверяем работу программу](./image/7.png){#fig:001 width=70%}

Скачаем файл in_out.asm со страницы курса в ТУИС.

[Скачиваем файл](./image/8.png){#fig:001 width=70%}

С помощью функциональной клавиши F6 создаем копию файла lab5-1.asm с именем lab5-2.asm. Выделяем файл lab5-1.asm, нажмем клавишу F6, введите имя файла lab5-2.asm и нажмем клавишу Enter (рис. 5.8).

[Создаем и проверяем копию](./image/9.png){#fig:001 width=70%}

Открываем новый файл и заполняем его в соответствии с листингом

[Заполняем новый файл](./image/10.png){#fig:001 width=70%}

Транслируем и запускаем новый файл

[Запускаем новый файл](./image/11.png){#fig:001 width=70%}

Снова открываем файл для редактирования и меняем sprintLF на sprint

[Редактируем файл](./image/12.png){#fig:001 width=70%}

Транслируем и запускаем файл

[Запускаем файл](./image/13.png){#fig:001 width=70%}

Сравниваем вывод двух программ: функция sprint выводит текст в той же строке, в отличие от sprintLF

# Самостоятельная работа

Создаем копию файла lab5-1.asm и называем его так же

[Создаем копию](./image/14.png){#fig:001 width=70%}

Редактируем файл, чтобы введеный текст с клавиатуры выводился в консоль

[Редактируем файл](./image/15.png){#fig:001 width=70%}


